name: Financial-Reporting
description: ''
version: 0.0.1
author: anshuman@simpledatalabs.com
language: python
pipelines:
  pipelines/load_acc_status_bronze:
    name: load_acc_status_bronze
    description: ''
    author: anshuman@simpledatalabs.com
    mode: batch
    language: python
    createdAt: '2022-05-25 09:30:11'
    datasets:
      inputs:
      - 5468/datasets/acc_status_external
      outputs:
      - 5468/datasets/acc_status_bronze
    dependencies: {}
  pipelines/load_transactions_bronze:
    name: load_transactions_bronze
    description: ''
    author: anshuman@simpledatalabs.com
    mode: batch
    language: python
    createdAt: '2022-05-25 13:11:54'
    datasets:
      inputs:
      - 5468/datasets/transactions_external
      outputs:
      - 5468/datasets/transactions_bronze
    dependencies: {}
datasets:
  datasets/acc_status_external:
    name: acc_status_external
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-25 09:39:48'
    physicalDatasets:
      recipes_fabric:
        fabricId: 1010
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-25 09:39:49'
  datasets/acc_status_bronze:
    name: acc_status_bronze
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-25 13:09:36'
    physicalDatasets:
      recipes_fabric:
        fabricId: 1010
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-25 13:09:36'
  datasets/transactions_external:
    name: transactions_external
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-25 13:14:29'
    physicalDatasets:
      recipes_fabric:
        fabricId: 1010
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-25 13:14:29'
  datasets/transactions_bronze:
    name: transactions_bronze
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-25 13:47:24'
    physicalDatasets:
      recipes_fabric:
        fabricId: 1010
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-25 13:47:24'
jobs: {}
libraries: []
subgraphs: {}
dependencies: '[]'
template: '[]'
