name: Financial-Reporting
description: ''
version: 0.0.1
author: anshuman@simpledatalabs.com
language: python
pipelines:
  pipelines/data_generator:
    name: data_generator
    description: ''
    author: anshuman@simpledatalabs.com
    mode: batch
    language: python
    createdAt: '2022-05-25 14:59:22'
    datasets:
      inputs: []
      outputs:
      - 5468/datasets/acc_status_external_20220504
      - 5468/datasets/acc_status_external_20220505
      - 5468/datasets/transactions_external_20220505
      - 5468/datasets/person_external_20220505
      - 5468/datasets/products_external_20220505
    dependencies: {}
  pipelines/load_acc_status_bronze:
    name: load_acc_status_bronze
    description: ''
    author: anshuman@simpledatalabs.com
    mode: batch
    language: python
    createdAt: '2022-05-25 09:30:11'
    datasets:
      inputs:
      - 5468/datasets/acc_status_external
      outputs:
      - 5468/datasets/acc_status_bronze
    dependencies: {}
  pipelines/load_person_bronze:
    name: load_person_bronze
    description: ''
    author: anshuman@simpledatalabs.com
    mode: batch
    language: python
    createdAt: '2022-05-25 14:01:35'
    datasets:
      inputs:
      - 5468/datasets/person_external
      outputs:
      - 5468/datasets/person_bronze
    dependencies: {}
  pipelines/load_transactions_silver:
    name: load_transactions_silver
    description: ''
    author: anshuman@simpledatalabs.com
    mode: batch
    language: python
    createdAt: '2022-05-26 06:56:51'
    datasets:
      inputs:
      - 5468/datasets/transactions_bronze
      - 5468/datasets/acc_status_silver
      outputs:
      - 5468/datasets/transactions_silver
    dependencies: {}
  pipelines/load_transactions_bronze:
    name: load_transactions_bronze
    description: ''
    author: anshuman@simpledatalabs.com
    mode: batch
    language: python
    createdAt: '2022-05-25 13:11:54'
    datasets:
      inputs:
      - 5468/datasets/transactions_external
      outputs:
      - 5468/datasets/transactions_bronze
    dependencies: {}
  pipelines/load_products_bronze:
    name: load_products_bronze
    description: ''
    author: anshuman@simpledatalabs.com
    mode: batch
    language: python
    createdAt: '2022-05-25 13:48:49'
    datasets:
      inputs:
      - 5468/datasets/products_external
      outputs:
      - 5468/datasets/products_bronze
    dependencies: {}
  pipelines/load_acc_status_silver:
    name: load_acc_status_silver
    description: ''
    author: anshuman@simpledatalabs.com
    mode: batch
    language: python
    createdAt: '2022-05-26 06:43:29'
    datasets:
      inputs:
      - 5468/datasets/acc_status_bronze
      outputs:
      - 5468/datasets/acc_status_silver
    dependencies: {}
datasets:
  datasets/acc_status_external_20220505:
    name: acc_status_external_20220505
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-25 15:26:53'
    physicalDatasets:
      recipes_fabric:
        fabricId: 1010
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-25 15:26:53'
  datasets/transactions_external:
    name: transactions_external
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-25 13:14:29'
    physicalDatasets:
      recipes_fabric:
        fabricId: 1010
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-25 13:14:29'
  datasets/acc_status_external:
    name: acc_status_external
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-25 09:39:48'
    physicalDatasets:
      recipes_fabric:
        fabricId: 1010
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-25 09:39:49'
  datasets/person_external_20220505:
    name: person_external_20220505
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-25 15:46:01'
    physicalDatasets:
      recipes_fabric:
        fabricId: 1010
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-25 15:46:01'
  datasets/products_bronze:
    name: products_bronze
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-25 13:51:49'
    physicalDatasets:
      recipes_fabric:
        fabricId: 1010
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-25 13:51:49'
  datasets/acc_status_bronze:
    name: acc_status_bronze
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-25 13:09:36'
    physicalDatasets:
      recipes_fabric:
        fabricId: 1010
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-25 13:09:36'
  datasets/products_external:
    name: products_external
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-25 13:50:49'
    physicalDatasets:
      recipes_fabric:
        fabricId: 1010
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-25 13:50:49'
  datasets/person_external:
    name: person_external
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-25 14:03:17'
    physicalDatasets:
      recipes_fabric:
        fabricId: 1010
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-25 14:03:17'
  datasets/transactions_external_20220505:
    name: transactions_external_20220505
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-25 15:33:43'
    physicalDatasets:
      recipes_fabric:
        fabricId: 1010
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-25 15:33:43'
  datasets/transactions_silver:
    name: transactions_silver
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-26 07:01:53'
    physicalDatasets:
      recipes_fabric:
        fabricId: 1010
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-26 07:01:53'
  datasets/acc_status_silver:
    name: acc_status_silver
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-26 06:53:09'
    physicalDatasets:
      recipes_fabric:
        fabricId: 1010
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-26 06:53:09'
  datasets/products_external_20220505:
    name: products_external_20220505
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-25 15:47:48'
    physicalDatasets:
      recipes_fabric:
        fabricId: 1010
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-25 15:47:48'
  datasets/person_bronze:
    name: person_bronze
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-25 14:03:57'
    physicalDatasets:
      recipes_fabric:
        fabricId: 1010
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-25 14:03:57'
  datasets/acc_status_external_20220504:
    name: acc_status_external_20220504
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-25 15:24:00'
    physicalDatasets:
      recipes_fabric:
        fabricId: 1010
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-25 15:24:00'
  datasets/transactions_bronze:
    name: transactions_bronze
    description: ''
    author: anshuman@simpledatalabs.com
    createdAt: '2022-05-25 13:47:24'
    physicalDatasets:
      recipes_fabric:
        fabricId: 1010
        datasetType: File
        description: ''
        author: anshuman@simpledatalabs.com
        createdAt: '2022-05-25 13:47:24'
jobs: {}
libraries: []
subgraphs: {}
dependencies: []
template: '[]'
